// Copyright (c) 2026 Viva Las Mesh Authors
// SPDX-License-Identifier: MIT

// Package game provides gameplay systems for Viva Las Mesh Layer 2.
// This is Layer 2 (Game Mechanics) - Gameplay systems (attrs, items, NPCs, missions).
package game

// SkimChannel represents the different money laundering channels available through "The Skim".
type SkimChannel string

const (
	SkimChannelCraps      SkimChannel = "LN-CRAPS" // High-stakes craps
	SkimChannelDispensary SkimChannel = "LN-DISP"  // Dispensary retail
	SkimChannelPawnshop   SkimChannel = "LN-PAWN"  // Pawn shops
	SkimChannelCountroom  SkimChannel = "LN-CAGE"  // Casino count rooms
)

// SkimFee returns the fee percentage (as a float between 0 and 1) for a given channel.
// In a real implementation, these might be dynamic based on reputation, heat, etc.
func SkimFee(channel SkimChannel) float64 {
	switch channel {
	case SkimChannelCraps:
		return 0.15 // 15% fee
	case SkimChannelDispensary:
		return 0.12 // 12% fee
	case SkimChannelPawnshop:
		return 0.18 // 18% fee
	case SkimChannelCountroom:
		return 0.10 // 10% fee (count rooms have lower fees due to volume)
	default:
		return 0.20 // Default 20% fee
	}
}

// LaunderMoney processes an amount through a Skim channel, returning the laundered amount
// after deducting the fee. It also returns the fee amount that could be used to generate
// police heat (since money laundering attracts attention).
func LaunderMoney(amount float64, channel SkimChannel) (laundered, fee float64) {
	if amount < 0 {
		amount = 0
	}
	feePercent := SkimFee(channel)
	fee = amount * feePercent
	laundered = amount - fee
	return laundered, fee
}

// HeatFromSkim returns the amount of police heat generated by laundering a given amount
// through a channel. In a real implementation, this would depend on the fee, the channel,
// and current heat level. For simplicity, we return a flat heat increase based on fee.
func HeatFromSkim(fee float64) int {
	// Convert fee to heat points: every 10% fee generates 1 heat point, capped at 5 per transaction?
	// We'll just return a small integer.
	heat := int(fee * 10) // e.g., fee of 0.15 (15%) -> 1.5 -> 1 heat point
	if heat > 5 {
		heat = 5
	}
	return heat
}
